### ISSUE TITLE
Post-intl audit tracker

### ISSUE THREAD

**Issue by wackerow** [ethereum/eth2.0-deposit#378]
Tracking issue for auditing `master` branch (live on https://pyrmont.launchpad.ethereum.org) after large `translations` branch merge.
### Important findings:
- [x] Acknowledgement links derailing users (fixed in #376)
- [x] Beacon chain explorer links broken (fixed in #377, thanks for these @hwwhww!)
- [x] `ENABLE_RPC_FEATURES` seems to be evaluating to `false`, which should only happen if there is no `REACT_APP_INFURA_PROJECT_ID` provided by the `.env`. Below shows live Pyrmont page on the left, and locally served `master` branch on the right:
![image](https://user-images.githubusercontent.com/54227730/110681913-3128dc80-818f-11eb-9eb5-81091bfeb2d2.png)
@CarlBeek @hwwhww can we confirm this `REACT_APP_INFURA_PROJECT_ID` constant is made available?

### Less critical things I noted:
- [x] Double external link arrow showing for Etherscan on Top-Up modal
![image](https://user-images.githubusercontent.com/54227730/110688799-d5625180-8196-11eb-8e39-f9b80ebcc836.png)
- [x] "Top up" wrapping
![image](https://user-images.githubusercontent.com/54227730/110681221-6da80880-818e-11eb-891f-dd01bc1ce7b9.png)
- [x] Anchor link extends beyond buttons when they wrap on landing `<Hero />` and `<NetworkStatus />` components
![image](https://user-images.githubusercontent.com/54227730/110680883-025e3680-818e-11eb-8a75-8e226dfd431d.png)
- [x] `Confirm deposits (1)` - could make this conditional like other strings here. ie. if only one deposit just say `Confirm deposit`.
![image](https://user-images.githubusercontent.com/54227730/110687708-ab5c5f80-8195-11eb-95bf-39bf529c2efa.png)

Feel free to drop other related issues you may find in the comments. I'll work to fix these up, but need a hand with the `.env` constants. =)

**Comment by samajammin** [comment]
Nice finds @wackerow! I support fixing / making all these updates you mentioned.

I pinged devops about the `REACT_APP_INFURA_PROJECT_ID` (see the issue linked above).

**Comment by OGKEEKS** [comment]
i want to helpby being a validator.

**Comment by hwwhww** [comment]
@wackerow @samajammin 
👋 I just replied on the DevOps issue ticket.

**Comment by wackerow** [comment]
The above merge should fix everything I mentioned initially. Removed the check for `ENABLE_RPC_FEATURES` (which is a boolean based on if the Infura API keys are available in the `.env` file) for the features that now use Beaconcha.in as the endpoint. 
The Fortmatic wallet appears to still have logic utilizing these variables. Discussion about `REACT_APP_INFURA_PROJECT_ID` at https://github.com/ethereum/devops/issues/638
Will leave this open until that is clarified.

**Comment by samajammin** [comment]
Solved in #379 - thanks @wackerow!
